user:
  dev:
    name: HRDEV
    password_env_var: HR_PASSWORD
  prd:
    name: HR
    password_env_var: HR_PASSWORD
dbtype: oracle
aximatadb_user: 
  name: AXIMATA
connection_strings:
  dev: oracle-19c-test:1521/ORCLPDB1
  prd: oracle-19c-test:1521/ORCLPDB1