-- @env: default
CREATE OR REPLACE EDITIONABLE TRIGGER HR.SECURE_EMPLOYEES
  BEFORE INSERT OR UPDATE OR DELETE ON employees
BEGIN
  secure_dml;
END secure_employees;
/
-- @env: default
ALTER TRIGGER HR.SECURE_EMPLOYEES DISABLE;