-- @env: default
CREATE TABLE HR.COUNTRIES
(
    COUNTRY_ID CHAR(2) CONSTRAINT COUNTRY_ID_NN NOT NULL,
    COUNTRY_NAME VARCHAR2(40),
    REGION_ID NUMBER,
    CONSTRAINT COUNTRY_C_ID_PK PRIMARY KEY (COUNTRY_ID),
    CONSTRAINT COUNTR_REG_FK FOREIGN KEY (REGION_ID)
    REFERENCES HR.REGIONS (REGION_ID)) SEGMENT CREATION IMMEDIATE
    ORGANIZATION INDEX NOCOMPRESS PCTFREE 10 INITRANS 2 MAXTRANS 255 LOGGING
    PCTTHRESHOLD 50;