-- @env: default
CREATE TABLE HR.DEPARTMENTS
(
    DEPARTMENT_ID NUMBER(4,0),
    DEPARTMENT_NAME VARCHAR2(30) CONSTRAINT DEPT_NAME_NN NOT NULL,
    MANAGER_ID NUMBER(6,0),
    LOCATION_ID NUMBER(4,0),
    CONSTRAINT DEPT_LOC_FK FOREIGN KEY (LOCATION_ID)
    REFERENCES HR.LOCATIONS (LOCATION_ID),
    CONSTRAINT DEPT_MGR_FK FOREIGN KEY (MANAGER_ID)
    REFERENCES HR.EMPLOYEES (EMPLOYEE_ID)) ;

-- @env: default
CREATE UNIQUE INDEX HR.DEPT_ID_PK ON HR.DEPARTMENTS (
    DEPARTMENT_ID)
    ;

-- @env: default
ALTER TABLE HR.DEPARTMENTS ADD CONSTRAINT DEPT_ID_PK PRIMARY KEY (DEPARTMENT_ID);