-- @env: default
CREATE TABLE HR.JOB_HISTORY
(
    EMPLOYEE_ID NUMBER(6,0) CONSTRAINT JHIST_EMPLOYEE_NN NOT NULL,
    START_DATE DATE CONSTRAINT JHIST_START_DATE_NN NOT NULL,
    END_DATE DATE CONSTRAINT JHIST_END_DATE_NN NOT NULL,
    JOB_ID VARCHAR2(10) CONSTRAINT JHIST_JOB_NN NOT NULL,
    DEPARTMENT_ID NUMBER(4,0),
    CONSTRAINT JHIST_DATE_INTERVAL CHECK (end_date > start_date),
    CONSTRAINT JHIST_JOB_FK FOREIGN KEY (JOB_ID)
    REFERENCES HR.JOBS (JOB_ID),
    CONSTRAINT JHIST_EMP_FK FOREIGN KEY (EMPLOYEE_ID)
    REFERENCES HR.EMPLOYEES (EMPLOYEE_ID),
    CONSTRAINT JHIST_DEPT_FK FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES HR.DEPARTMENTS (DEPARTMENT_ID)) ;

-- @env: default
CREATE UNIQUE INDEX HR.JHIST_EMP_ID_ST_DATE_PK ON HR.JOB_HISTORY (
    EMPLOYEE_ID, START_DATE)
    ;

-- @env: default
ALTER TABLE HR.JOB_HISTORY ADD CONSTRAINT JHIST_EMP_ID_ST_DATE_PK PRIMARY KEY (EMPLOYEE_ID, START_DATE);