-- @env: default
CREATE TABLE HR.JOBS
(
    JOB_ID VARCHAR2(10),
    JOB_TITLE VARCHAR2(35) CONSTRAINT JOB_TITLE_NN NOT NULL,
    MIN_SALARY NUMBER(6,0),
    MAX_SALARY NUMBER(6,0)
);

-- @env: default
CREATE UNIQUE INDEX HR.JOB_ID_PK ON HR.JOBS (
    JOB_ID)
    ;

-- @env: default
ALTER TABLE HR.JOBS ADD CONSTRAINT JOB_ID_PK PRIMARY KEY (JOB_ID);