-- @env: default
CREATE TABLE HR.LOCATIONS
(
    LOCATION_ID NUMBER(4,0),
    STREET_ADDRESS VARCHAR2(40),
    POSTAL_CODE VARCHAR2(12),
    CITY VARCHAR2(30) CONSTRAINT LOC_CITY_NN NOT NULL,
    STATE_PROVINCE VARCHAR2(25),
    COUNTRY_ID CHAR(2),
    CONSTRAINT LOC_C_ID_FK FOREIGN KEY (COUNTRY_ID)
    REFERENCES HR.COUNTRIES (COUNTRY_ID)) ;

-- @env: default
CREATE UNIQUE INDEX HR.LOC_ID_PK ON HR.LOCATIONS (
    LOCATION_ID)
    ;

-- @env: default
ALTER TABLE HR.LOCATIONS ADD CONSTRAINT LOC_ID_PK PRIMARY KEY (LOCATION_ID);