-- @env: default
CREATE TABLE HR.REGIONS
(
    REGION_ID NUMBER CONSTRAINT REGION_ID_NN NOT NULL,
    REGION_NAME VARCHAR2(25)
);

-- @env: default
CREATE UNIQUE INDEX HR.REG_ID_PK ON HR.REGIONS (
    REGION_ID)
    ;

-- @env: default
ALTER TABLE HR.REGIONS ADD CONSTRAINT REG_ID_PK PRIMARY KEY (REGION_ID);