-- @env: default
CREATE USER HR IDENTIFIED BY "{{password}}"
    DEFAULT TABLESPACE USERS
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED ON DEV_DATA
    QUOTA UNLIMITED ON USERS;

-- @env: default
GRANT ALTER SESSION TO HR;
-- @env: default
GRANT CREATE DATABASE LINK TO HR;
-- @env: default
GRANT CREATE SEQUENCE TO HR;
-- @env: default
GRANT CREATE SESSION TO HR;
-- @env: default
GRANT CREATE SYNONYM TO HR;
-- @env: default
GRANT CREATE TABLE TO HR;
-- @env: default
GRANT CREATE VIEW TO HR;
-- @env: default
GRANT UNLIMITED TABLESPACE TO HR;
-- @env: default
GRANT RESOURCE TO HR;